const { join } = require('path')

const getHomeDir = require('./utils/get-home-dir')

module.exports = {
  EXTENSION_NAME: 'awsCfnAutoTemplateGenerator',

  DESCRIBE_TYPE_CACHE_TTL_CONFIGURATION_PROPERTY: 'describeTypeCacheTtl',
  LIST_TYPES_CACHE_TTL_CONFIGURATION_PROPERTY: 'listTypesCacheTtl',
  PROFILE_CONFIGURATION_PROPERTY: 'profile',
  REGION_CONFIGURATION_PROPERTY: 'region',
  RESOURCE_VISIBILITY_CONFIGURATION_PROPERTY: 'resourceVisibility',
  TEMPLATE_FORMAT_CONFIGURATION_PROPERTY: 'templateFormat',
  CONFIG_FILE_PATH_CONFIGURATION_PROPERTY: 'configFilePath',

  PUBLIC_TYPE_LIST_CACHE_TTL_DAYS: 1,
  PUBLIC_TYPE_CACHE_TTL_DAYS: 1,

  PRIVATE_TYPE_LIST_CACHE_TTL_DAYS: 1,
  PRIVATE_TYPE_CACHE_TTL_DAYS: 1,

  VALID_TEMPLATE_FORMATS: ['yaml', 'json'],
  DEFAULT_TEMPLATE_FORMAT: 'yaml',

  DEFAULT_CONFIG_FILE_PATH: join(getHomeDir(), '.aws', 'config'),

  VALID_RESOURCE_VISIBILITY_OPTIONS: ['PUBLIC', 'PRIVATE'],
  DEFAULT_RESOURCE_VISIBILITY: 'PUBLIC'
}
